version: "3.7"

services:
  cassandra-1:
    image: cassandra:4.1.0
    container_name: "cassandra-1"
    hostname: "cassandra-1"
    environment:
      CASSANDRA_CLUSTER_NAME: "cas-cluster"
      CASSANDRA_SEEDS: "cassandra-1, cassandra-2, cassandra-3"
      CASSANDRA_BROADCAST_ADDRESS: 172.16.10.10
    ports:
      - "7000:7000"
      - "9042:9042"
    restart: unless-stopped
    networks:
      cas:
        ipv4_address: 172.16.10.10
    volumes:
      - "cassandra_1:/var/lib/cassandra"

  cassandra-2:
    image: cassandra:4.1.0
    container_name: "cassandra-2"
    hostname: "cassandra-2"
    environment:
      CASSANDRA_CLUSTER_NAME: "cas-cluster"
      CASSANDRA_BROADCAST_ADDRESS: 172.16.10.11
      CASSANDRA_SEEDS: "cassandra-1, cassandra-2, cassandra-3"
    ports:
      - "7001:7000"
      - "9043:9042"
    restart: unless-stopped
    depends_on:
      - "cassandra-1"
    networks:
      cas:
         ipv4_address: 172.16.10.11
    volumes:
      - "cassandra_2:/var/lib/cassandra"

  cassandra-3:
    image: cassandra:4.1.0
    container_name: "cassandra-3"
    hostname: "cassandra-3"
    environment:
      CASSANDRA_CLUSTER_NAME: "cas-cluster"
      CASSANDRA_BROADCAST_ADDRESS: 172.16.10.12
      CASSANDRA_SEEDS: "cassandra-1, cassandra-2, cassandra-3"
    ports:
      - "7002:7000"
      - "9044:9042"
    restart: unless-stopped
    depends_on:
      - "cassandra-2"
    networks:
      cas:
         ipv4_address: 172.16.10.12
    volumes:
      - "cassandra_3:/var/lib/cassandra"


networks:
  cas:
    ipam:
      config:
        - subnet: 172.16.10.0/24

volumes:
  cassandra_1:
  cassandra_2:
  cassandra_3:
